# theme: jekyll-theme-minimal
title: VIKAS SINGH
description: Data Science Lead
title: "My Resume"
description: "Professional Resume"
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom settings
sass:
  style: compressed

# Build settings
baseurl: "/Vikas-CV"# the subpath of your site, e.g. /blog
url: "https://singhvks.github.io/" # the base hostname & protocol for your site 

# Includes custom CSS
markdown: kramdown
